version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "America/Chicago"
    assignees:
      - "spencerjanssen"
    reviewers:
      - "spencerjanssen"
