#!/bin/sh

# gnome-session --session xmonad-gnome-nopanel &
xmodmap .Xmodmap
taffybar &
nm-applet &
dropbox &
xset dpms 300 300 300
xset s off
nitrogen --set-tiled wallpaper/wallpaper.jpg
pidgin &
slack &

dbus-launch xmonad
