[formatter.nixpkgs-fmt]
command = "nixpkgs-fmt"
includes = [
    "*.nix"
]
excludes = [
    "nixos/imladris/*.nix"
]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = [
    "*.yml",
    "*.yaml"
]
