[formatter.nixpkgs-fmt]
command = "nixpkgs-fmt"
includes = [
    "*.nix"
]
excludes = [
    "nixos/imladris/*.nix"
]

[formatter.yamlfmt]
command = "yamlfmt"
options = []
includes = [
    "*.yml",
    "*.yaml"
]
