# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.loader.efi.canTouchEfiVariables = false;
  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6afd67b5-af9c-4418-aabd-fb844f10eeed";
      fsType = "btrfs";
      options = [ "subvol=@nixos" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/6afd67b5-af9c-4418-aabd-fb844f10eeed";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/media/ssd" =
    { device = "/dev/disk/by-uuid/6afd67b5-af9c-4418-aabd-fb844f10eeed";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/546C-278E";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/f8637202-2cbf-4928-a0c2-a766eae954ff"; }
    ];

  nix.maxJobs = 4;
}
