name: flake check
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - flake-update
jobs:
  check:
    name: Check flake
    runs-on: [self-hosted, dotfiles-builder]
    steps:
      - run: |
          nix flake check --print-build-logs --keep-going --all-systems github:spencerjanssen/dotfiles/$GITHUB_SHA
