name: flake check
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - flake-update
jobs:
  check:
    name: Check flake
    runs-on: [self-hosted, dotfiles-builder]
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - run: nix flake check --print-build-logs --keep-going --all-systems .
      - name: Trigger upgrade
        if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        run: systemctl start --wait nixos-upgrade.service
