name: flake check
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - flake-update
      - fix-auto-upgrade
jobs:
  check:
    name: Check flake
    runs-on: [self-hosted, dotfiles-builder]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: nix flake check --print-build-logs --keep-going --all-systems .
      - name: Trigger upgrade
        if: github.ref == 'refs/heads/fix-auto-upgrade' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        run: |
          echo "Debugging systemd environment:"
          echo "DBUS_SESSION_BUS_ADDRESS: $DBUS_SESSION_BUS_ADDRESS"
          echo "DBUS_SYSTEM_BUS_ADDRESS: $DBUS_SYSTEM_BUS_ADDRESS"
          echo "USER: $USER"
          echo "Groups: $(groups)"
          echo "Systemd version: $(systemctl --version | head -1)"
          echo "Trying to list systemd units:"
          systemctl list-units --type=service --state=active | grep nixos || true
          echo "Attempting to start nixos-upgrade.service:"
          sudo systemctl start --wait nixos-upgrade.service
