name: Trigger Hydra Eval on PR
on:
  pull_request:
    types: [opened, closed, reopened]
jobs:
  poke_hydra:
    name: Trigger Hydra Eval
    runs-on: ubuntu-latest
    steps:
      - name: Call API
        run: |
          curl --retry 30 -X PUT "https://${{ secrets.HYDRA_HOST }}/api/push?jobsets=dotfiles-prs:.jobsets"
